name: Publish Package to NPM
on:
  push:
    branches:
      - production
jobs:
  check-if-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
  
  publish-to-npm:
    needs: check-if-new-version
    if: ${{ needs.check-if-new-version.outputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo ${{ needs.check-if-new-version.outputs.tag }}
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
