name: Publish Package to NPM
on:
  push:
    branches:
      - production

jobs:
  publish:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check for new version
        uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-new-version
      
      - name: Publish to NPM
        # if: steps.detect-new-version.outputs.tag != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo ${{ needs.check-if-new-version.outputs.tag }}
          sudo npm install -g pnpm

          pnpm install
          pnpm publish --publish-branch production --access public
